#!/usr/bin/env bash
if [ $# -lt 3 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  file=$1
  ip=$2
  user=$3
  priv_key=$4
  scp -o StrictHostKeyChecking=no -i "$priv_key" "$file" "$user@$ip":~ 
fi
