#!/usr/bin/env bash
apt-get update
apt-get install -y nginx
# Allow Nginx traffic on port 80
ufw allow 'Nginx HTTP'
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
     location /redirect_me {
        return 301 http://msn.com/;
     }
}
" > /etc/nginx/sites-available/default

nginx -s reload
