#!/usr/bin/env bash
# configuring nginx with a custom 404-Not found page
apt-get update
apt-get install -y nginx
# Allow Nginx traffic on port 80
ufw allow 'Nginx HTTP'
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
     location /redirect_me {
        return 301 http://msn.com/;
     }
     error_page 404 /404.html;
     location /404 {
        root /etc/nginx/html;
        internal;
     }
}
" > /etc/nginx/sites-available/default

nginx -s reload
