#!/usr/bin/env bash
# Script that installs HAproxy and configures it to distribute requests to two webservers using a roundrobin algorithm
apt-get update
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0 -y
apt-get install -y haproxy=2.0.\*

cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    option redispatch
    timeout connect 5000
    timeout client 10000
    timeout server 10000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 108938-web-01 52.87.216.43:80 check
    server 108938-web-02 100.25.180.60:80 check
EOF

systemctl enable haproxy.service
service haproxy restart
