#!/usr/bin/env bash
# script that creates the file /var/run/myscript.pid containing its PID,
# displays "To infinity and beyond",
# displays "I hate the kill command" when receiving a SIGTERM signal,
# displays "Y U no love me?!" when receiving a SIGINT signal
# deletes the file /var/run/myscript.pid and terminates itself when
#+ receiving a SIGQUIT or SIGTERM signal

pgrep -f 100-process_and_pid_file | sudo tee /var/run/myscript.pid
while true;
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo 'I hate the kill command'; sudo rm -f /var/run/myscript.pid; exit" SIGTERM
	trap "echo 'Y U no love me?!'; exit" SIGINT
	trap "sudo rm -f /var/run/myscript.pid; exit" SIGQUIT
done
