#!/usr/bin/env bash
# Prints string indefinitly and prints another string when process receives a SIGTERM signal

while true;
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo 'I am invincible!!!'" SIGTERM
done
