#!/usr/bin/env bash
# List numbers 1-100 displaying FizzBuzz for multiples of 3 and 5, Fizz for multiples of 3, Buzz for multiples of 5

i=1
while ((i<=100))
do
	if [[ $((i%3)) -eq 0 ]] && [[ $((i%5)) -eq 0 ]]; then
		echo "FizzBuzz"
	elif [[ $((i%3)) -eq 0 ]]; then
		echo "Fizz"
	elif [[ $((i%5)) -eq 0 ]]; then
		echo "Buzz"
	else
		echo "$i"
	fi
	((i++))
done
