#!/usr/bin/env bash
# Script to display the content of the file /etc/passwd
# displays the username, user id and user home directoy path
while read -r passwd; do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
