#!/usr/bin/env bash
# Displays the content of the file /etc/passwd
# Displays on the username, user id and home directory of the user

fl="/etc/passwd"
while read -r passwd;
do
	echo "$passwd" | cut -d ':' -f1,3,6
done < $fl
