#!/usr/bin/env bash
# Loops from 1 to 10 printing bad luck and good luck for 4th and 8th iteration and Best School for the rest

i=1
while ((i<=10));
	do
		if [ $i -eq 4 ]; then
			echo "bad luck"
		elif [ $i -eq 8 ]; then
			echo "good luck"
		else
			echo "Best School"
		fi
	((i++))
done
